/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-06 09:04:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class personInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/inc/header.jsp", Long.valueOf(1725504021918L));
    _jspx_dependants.put("/view/inc/personSideNav.jsp", Long.valueOf(1725504021920L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>personInfo</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".container.my .content_area {\r\n");
      out.write("	min-height: 380px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content_area {\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-page-content {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my_profile {\r\n");
      out.write("	padding: 0 24px 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content_title {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content_title.border {\r\n");
      out.write("	border-bottom: 3px solid #222;\r\n");
      out.write("	padding-bottom: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	letter-spacing: -.36px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title>h3 {\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	line-height: 29px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*user 사진관리 start */\r\n");
      out.write(".user_profile {\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	padding: 38px 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lg .user_profile {\r\n");
      out.write("	border-bottom: 1px solid #ebebeb\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_thumb {\r\n");
      out.write("	border-radius: 100%;\r\n");
      out.write("	flex: none;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	margin-right: 12px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	width: 80px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lg .profile_thumb {\r\n");
      out.write("	height: 90px;\r\n");
      out.write("	width: 90px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_thumb .thumb_img {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	-o-object-fit: cover;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_detail .name {\r\n");
      out.write("	margin-top: 3px;\r\n");
      out.write("	color: #000;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	letter-spacing: -.27px;\r\n");
      out.write("	line-height: 1.2222222222\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_detail .div_user {\r\n");
      out.write("	color: #ebebeb;;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	letter-spacing: -.27px;\r\n");
      out.write("	line-height: 1.2222222222\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_btn_box {\r\n");
      out.write("	font-size: 0;\r\n");
      out.write("	margin-top: 12px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_btn_box .btn+.btn {\r\n");
      out.write("	margin-left: 8px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: rgba(34, 34, 34, .8);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display: inline-flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	vertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outlinegrey {\r\n");
      out.write("	border: 1px solid #d3d3d3;\r\n");
      out.write("	color: rgba(34, 34, 34, .8)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outlinegrey:active {\r\n");
      out.write("	background-color: #f4f4f4;\r\n");
      out.write("	border-color: #ebebeb;\r\n");
      out.write("	color: rgba(34, 34, 34, .5)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".small {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	height: 34px;\r\n");
      out.write("	letter-spacing: -.06px;\r\n");
      out.write("	padding: 0 14px\r\n");
      out.write("}\r\n");
      out.write("/*user 사진관리 End */\r\n");
      out.write("\r\n");
      out.write("/*개인계정,개인정보 Start*/\r\n");
      out.write(".profile_info {\r\n");
      out.write("	padding-top: 38px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lg .profile_group {\r\n");
      out.write("	padding-top: 58px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_group {\r\n");
      out.write("	padding-top: 48px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_group:first-of-type {\r\n");
      out.write("	padding-top: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".group_title {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	letter-spacing: -.27px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modify.name {\r\n");
      out.write("	padding-top: 25px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".unit {\r\n");
      out.write("	border-bottom: 1px solid #ebebeb;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	padding: 25px 0 12px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".unit+.unit {\r\n");
      out.write("	padding-top: 23px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	color: rgba(34, 34, 34, .5);\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	letter-spacing: -.07px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".unit_content {\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".desc {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	letter-spacing: -.16px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	padding-bottom: 8px;\r\n");
      out.write("	padding-top: 8px;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	white-space: nowrap\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".desc_modify {\r\n");
      out.write("	padding-right: 58px\r\n");
      out.write("}\r\n");
      out.write("/*개인계정,개인정보 End*/\r\n");
      out.write(".btn_withdrawal {\r\n");
      out.write("	color: rgba(34, 34, 34, .5);\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	letter-spacing: -.07px;\r\n");
      out.write("	margin-top: 55px;\r\n");
      out.write("	padding: 5px 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*empty_area Start  */\r\n");
      out.write(".empty_area {\r\n");
      out.write("	padding: 81px 0 45px;\r\n");
      out.write("	text-align: center\r\n");
      out.write("}\r\n");
      out.write("/*empty_area End  */\r\n");
      out.write(".wrap {\r\n");
      out.write("	margin-top: 121px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Header Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DEVPanda|개발자 거래플랫폼</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: \"Nanum Gothic\", sans-serif;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #FFFEF7;\r\n");
      out.write("    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 100;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_logo {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".header_logo >span {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_logo img {\r\n");
      out.write("    max-height: 100px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_content {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-right: 100px;\r\n");
      out.write("    align-content: flex-end;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_top {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    padding-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_top .top_list {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_top .top_item + .top_item {\r\n");
      out.write("    margin-left: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_top .top_link {\r\n");
      out.write("    color: rgba(34, 34, 34, .8);\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    letter-spacing: -.06px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .header_main {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write("/* .header_main .gnb_area {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(".header_main .gnb_list {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_main .gnb_item + .gnb_item {\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header_main .gnb_link {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"header_logo\">\r\n");
      out.write("            <a href=\"main.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoS.png\" alt=\"DevPanda Logo\"></a>\r\n");
      out.write("        	<span>DevPanda</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header_content\">\r\n");
      out.write("    <!--         <div class=\"header_top\">\r\n");
      out.write("                <ul class=\"top_list\">\r\n");
      out.write("                    <li class=\"top_item\"><a class=\"top_link\" href=\"./personInfo.jsp\">마이페이지</a></li>\r\n");
      out.write("                    <li class=\"top_item\"><a class=\"top_link\" href=\"#notifications\">알림</a></li>\r\n");
      out.write("                    <li class=\"top_item\"><a class=\"top_link\" href=\"/\">로그아웃</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"header_main\">\r\n");
      out.write("                <div class=\"gnb_area\">\r\n");
      out.write("                    <nav class=\"gnb\" id=\"pcGnbContainer\">\r\n");
      out.write("                        <ul class=\"gnb_list\" id=\"pcGnbList\">\r\n");
      out.write("                            <li class=\"gnb_item\"><a class=\"gnb_link\" href=\"main.jsp\">AUCTION</a></li>\r\n");
      out.write("                            <li class=\"gnb_item\"><a class=\"gnb_link\" href=\"personInfo.jsp\">MYPAGE</a></li>\r\n");
      out.write("                            <li class=\"gnb_item\"><a class=\"gnb_link\" href=\"personInfo.jsp\">LOGOUT</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("	<!-- Header End-->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container my\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DEVPanda|개발자 거래플랫폼</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(" button, dd, div, dl, dt, fieldset, figcaption, figure, form, h1,\r\n");
      out.write("	h2, h3, h4, h5, h6, input, legend, li, ol, p, select, table, td,\r\n");
      out.write("	textarea, th, ul {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	font-family: \"Nanum Gothic\", sans-serif;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	color:#222;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("a,a:active,a:focus,a:hover {\r\n");
      out.write("    -webkit-text-decoration: none;\r\n");
      out.write("    text-decoration: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 꽉 채워서*/\r\n");
      out.write("/* .container.my {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	padding: 40px 40px 160px 5px; \r\n");
      out.write("	border-bottom: 0;\r\n");
      out.write("}  \r\n");
      out.write("*/\r\n");
      out.write("/*중앙에배치*/\r\n");
      out.write(" .container.my{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    max-width: 1280px;\r\n");
      out.write("    padding: 200px 40px 160px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container.my .snb_area {\r\n");
      out.write("	margin-right: 40px;\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height:90%;\r\n");
      out.write("	/* background-color: #f9f9f9; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container.my .snb_main_title {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	letter-spacing: -.36px;\r\n");
      out.write("	letter-spacing: -.15px;\r\n");
      out.write("	line-height: 29px;\r\n");
      out.write("	padding-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".snb_title {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	letter-spacing: -.27px;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("	margin-bottom: 12px;\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart_icon {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".snb_area+div {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 3px 0px 3px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item:hover {\r\n");
      out.write("    background-color: #f0f0f0; \r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("} /*수정한 부분*/ \r\n");
      out.write("\r\n");
      out.write(".menu_link {\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	letter-spacing: -.15px;\r\n");
      out.write("	line-height: 18px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".snb_list+.snb_list {\r\n");
      out.write("	margin-top: 40px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"snb_area\">\r\n");
      out.write("		<h2 class=\"snb_main_title\">마이 페이지</h2>\r\n");
      out.write("		<nav class=\"snb\">\r\n");
      out.write("			<div class=\"snb_list\">\r\n");
      out.write("				<strong class=\"snb_title\"> <svg class=\"cart_icon\" xmlns=\"http://www.w3.org/2000/svg\" height=\"21px\" viewBox=\"0 -960 960 960\" width=\"21px\" fill=\"#5f6368\">\r\n");
      out.write("							<path d=\"M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z\" /></svg> 구매내역조회\r\n");
      out.write("				</strong>\r\n");
      out.write("				<ul class=\"snb_menu\">\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../buyer/pNcBuyBidList.jsp\" class=\"menu_link\">입찰내역조회</a></li>\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../buyer/personBuyTransationList.jsp\" class=\"menu_link\">낙찰내역조회</a></li>\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../buyer/sellerBlack.jsp\" class=\"menu_link\">판매자 차단 내역</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"snb_list\">\r\n");
      out.write("				<strong class=\"snb_title\"><svg class=\"cart_icon\" xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\" width=\"24px\" fill=\"#5f6368\">\r\n");
      out.write("								<path d=\"M856-390 570-104q-12 12-27 18t-30 6q-15 0-30-6t-27-18L103-457q-11-11-17-25.5T80-513v-287q0-33 23.5-56.5T160-880h287q16 0 31 6.5t26 17.5l352 353q12 12 17.5 27t5.5 30q0 15-5.5 29.5T856-390ZM513-160l286-286-353-354H160v286l353 354ZM260-640q25 0 42.5-17.5T320-700q0-25-17.5-42.5T260-760q-25 0-42.5 17.5T200-700q0 25 17.5 42.5T260-640Zm220 160Z\" /></svg> 판매내역조회 </strong>\r\n");
      out.write("				<ul class=\"snb_menu\">\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../seller/personSellAcutionList.jsp\" class=\"menu_link\">경매등록 내역조회</a></li>\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../seller/personSellTransactionList.jsp\" class=\"menu_link\">낙찰내역조회</a></li>\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"../seller/buyerBlack.jsp\" class=\"menu_link\">구매자 차단 내역</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"snb_list\">\r\n");
      out.write("				<strong class=\"snb_title\"> <a> <svg class=\"cart_icon\" xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 0 24 24\" width=\"24px\" fill=\"#5f6368\">\r\n");
      out.write("								<path d=\"M0 0h24v24H0z\" fill=\"none\" /> \r\n");
      out.write("								<path d=\"M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z\" /></svg>\r\n");
      out.write("				</a> 내정보\r\n");
      out.write("				</strong>\r\n");
      out.write("				<ul class=\"snb_menu\">\r\n");
      out.write("					<li class=\"menu_item\"><a href=\"./personInfo.jsp\" class=\"menu_link\">정보수정</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- 로그인 정보 Start -->\r\n");
      out.write("		<div class=\"content_area my-page-content\">\r\n");
      out.write("			<div class=\"my_profile\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"content_title border\">\r\n");
      out.write("					<div class=\"title\">\r\n");
      out.write("						<h2>로그인 정보</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div style=\"margin-left: 10%;\">\r\n");
      out.write("					<!-- user 사진관리 start -->\r\n");
      out.write("					<div class=\"user_profile\">\r\n");
      out.write("						<input id=\"profileImageInput\" type=\"file\" accept=\"image/*\" hidden>\r\n");
      out.write("						<div class=\"profile_thumb\">\r\n");
      out.write("							<img id=\"profileImage\" src=\"./img/user2.png\" alt=\"사용자 이미지\"\r\n");
      out.write("								class=\"thumb_img\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"profile_detail\">\r\n");
      out.write("							<p class=\"div_user\">\r\n");
      out.write("								<strong>[개인회원]</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"name\">\r\n");
      out.write("								<strong>김자바</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("							<!-- js로 사진 업로드 구현해야 함 -->\r\n");
      out.write("							<div class=\"profile_btn_box\">\r\n");
      out.write("								<button id=\"changeImageButton\" type=\"button\"\r\n");
      out.write("									class=\"btn outlinegrey small\">이미지변경</button>\r\n");
      out.write("								<button id=\"deleteImageButton\" type=\"button\"\r\n");
      out.write("									class=\"btn outlinegrey small\">삭제</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<script>\r\n");
      out.write("						$(document)\r\n");
      out.write("								.ready(\r\n");
      out.write("										function() {\r\n");
      out.write("											// 이미지 변경 버튼 클릭 시 파일 선택창 열기\r\n");
      out.write("											$('#changeImageButton').click(\r\n");
      out.write("													function() {\r\n");
      out.write("														$('#profileImageInput')\r\n");
      out.write("																.click();\r\n");
      out.write("													});\r\n");
      out.write("\r\n");
      out.write("											// 파일 선택 시 이미지 미리보기 업데이트\r\n");
      out.write("											$('#profileImageInput')\r\n");
      out.write("													.change(\r\n");
      out.write("															function(event) {\r\n");
      out.write("																var reader = new FileReader();\r\n");
      out.write("																reader.onload = function(\r\n");
      out.write("																		e) {\r\n");
      out.write("																	$(\r\n");
      out.write("																			'#profileImage')\r\n");
      out.write("																			.attr(\r\n");
      out.write("																					'src',\r\n");
      out.write("																					e.target.result);// 여기서 이미지를 업데이트\r\n");
      out.write("																}\r\n");
      out.write("																reader\r\n");
      out.write("																		.readAsDataURL(event.target.files[0]);\r\n");
      out.write("															});\r\n");
      out.write("\r\n");
      out.write("											// 이미지 삭제 버튼 클릭 시 기본 이미지로 변경\r\n");
      out.write("											$('#deleteImageButton')\r\n");
      out.write("													.click(\r\n");
      out.write("															function() {\r\n");
      out.write("																$(\r\n");
      out.write("																		'#profileImage')\r\n");
      out.write("																		.attr(\r\n");
      out.write("																				'src',\r\n");
      out.write("																				'./img/user2.png'); // 기본 이미지로 변경\r\n");
      out.write("															});\r\n");
      out.write("										});\r\n");
      out.write("					</script>\r\n");
      out.write("					<!-- user 사진관리 end-->\r\n");
      out.write("\r\n");
      out.write("					<!-- 개인계정,개인정보 start -->\r\n");
      out.write("					<div class=\"profile_info\">\r\n");
      out.write("						<div class=\"profile_group\">\r\n");
      out.write("							<h4 class=\"group_title\">개인 계정</h4>\r\n");
      out.write("							<div class=\"unit\">\r\n");
      out.write("								<h5 class=\"title\">이메일 주소</h5>\r\n");
      out.write("								<div class=\"unit_content\">\r\n");
      out.write("									<p class=\"desc email\">kimjava@gmail.com</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<script>\r\n");
      out.write("								$(document)\r\n");
      out.write("										.ready(\r\n");
      out.write("												function() {\r\n");
      out.write("													$('.btn_modify')\r\n");
      out.write("															.click(\r\n");
      out.write("																	function() {\r\n");
      out.write("																		var $button = $(this);\r\n");
      out.write("																		var $emailField = $button\r\n");
      out.write("																				.siblings('.desc.email');\r\n");
      out.write("\r\n");
      out.write("																		// 만약 <p> 태그라면 input 태그로 변경\r\n");
      out.write("																		if ($emailField\r\n");
      out.write("																				.prop('tagName') === 'P') {\r\n");
      out.write("																			var email = $emailField\r\n");
      out.write("																					.text();\r\n");
      out.write("																			$emailField\r\n");
      out.write("																					.replaceWith('<input type=\"text\" class=\"desc email\" value=\"' + email + '\">');\r\n");
      out.write("																			$button\r\n");
      out.write("																					.text('저장');\r\n");
      out.write("																		}\r\n");
      out.write("																		// 만약 input 태그라면 p 태그로 변경\r\n");
      out.write("																		else if ($emailField\r\n");
      out.write("																				.prop('tagName') === 'INPUT') {\r\n");
      out.write("																			var updatedEmail = $emailField\r\n");
      out.write("																					.val();\r\n");
      out.write("																			$emailField\r\n");
      out.write("																					.replaceWith('<p class=\"desc email\">'\r\n");
      out.write("																							+ updatedEmail\r\n");
      out.write("																							+ '</p>');\r\n");
      out.write("																			$button\r\n");
      out.write("																					.text('변경');\r\n");
      out.write("																		}\r\n");
      out.write("																	});\r\n");
      out.write("												});\r\n");
      out.write("							</script>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"unit\">\r\n");
      out.write("								<h5 class=\"title\">비밀번호</h5>\r\n");
      out.write("								<div class=\"unit_content\">\r\n");
      out.write("									<p class=\"desc password\">●●●●●●●●●</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"profile_group\">\r\n");
      out.write("								<h4 class=\"group_title\">개인 정보</h4>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"unit\">\r\n");
      out.write("									<h5 class=\"title\">닉네임</h5>\r\n");
      out.write("									<div class=\"unit_content\">\r\n");
      out.write("										<p class=\"desc\">김자바</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"unit\">\r\n");
      out.write("									<h5 class=\"title\">성별</h5>\r\n");
      out.write("									<div class=\"unit_content\">\r\n");
      out.write("										<p class=\"desc\">남성</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"unit\">\r\n");
      out.write("									<h5 class=\"title\">나이</h5>\r\n");
      out.write("									<div class=\"unit_content\">\r\n");
      out.write("										<p class=\"desc\">20</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"unit\">\r\n");
      out.write("									<h5 class=\"title\">주소</h5>\r\n");
      out.write("									<div class=\"unit_content\">\r\n");
      out.write("										<p class=\"desc desc_modify placeholder\">서울특별시 금천구 독산동</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 개인계정,개인정보 End -->\r\n");
      out.write("					<div class=\"empty_area\">\r\n");
      out.write("						<a href=\"#\" data-v-420a5cda=\"\" class=\"btn outlinegrey small\">변경하기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"#\" class=\"btn_withdrawal\">회원 탈퇴</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 로그인 정보 End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
